### ISSUE TITLE
cvGs::Point2d and cvGs::crop  not implemented in fk space

### ISSUE THREAD

**Issue by albertandaluz** [morousg/cvGPUSpeedup#117]
in npp_batch_resize.cu , we can create a batch of crop recs, which we later use for batch cropping, ie
 
```cuda
std::array<cv::Rect2d, BATCH> crops_2d;
 for (int crop_i = 0; crop_i<BATCH; crop_i++) {
     crops_2d[crop_i] = cv::Rect2d(cv::Point2d(crop_i, crop_i), cv::Point2d(crop_i+60, crop_i+120));
 }
...
  std::array<cv::cuda::GpuMat, BATCH> crops;
  for (int crop_i=0; crop_i<BATCH; crop_i++) {
      crops[crop_i] = d_input(crops_2d[crop_i]);
....
      cvGS::executeOperations(cv_stream,
                              cvGS::resize<CV_TYPE_I, cv::INTER_LINEAR, BATCH>(crops, up, BATCH),
```
 However, we don't have similar funcionality for arrays declared as fk::Ptr2D<T>(W,H), so there is no way to easily crop 2d arrays representing images

**Comment by morousg** [comment]
We have already fk::Point and fk::Size implemented, but with a fixed data type. We also have crop implemented in fk::Ptr. There is another issue to implement crop as a separated DeviceFunction.

For this issue, we can make Point and Size template, and implement fk::Rect with the types also template.
